ALTER TABLE public.orders
ADD COLUMN subtotal_usd NUMERIC(12,2) DEFAULT 0 NOT NULL,
ADD COLUMN subtotal_afn NUMERIC(12,2) DEFAULT 0 NOT NULL,
ADD COLUMN delivery_fee_afn NUMERIC(12,2) DEFAULT 0 NOT NULL,
ADD COLUMN total_usd NUMERIC(12,2) DEFAULT 0 NOT NULL,
ADD COLUMN total_afn NUMERIC(12,2) DEFAULT 0 NOT NULL,
ADD COLUMN settlement_currency TEXT NOT NULL DEFAULT 'AFN' CHECK (settlement_currency IN ('AFN', 'USD'));